version: '3.2'

services:
  nginx:
    build: ./docker/nginx
    image: project-nginx
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build: ./docker/php/
    image: project-php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./src/app:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    build: ./docker/mysql
    image: project-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - project-database:/var/lib/mysql

volumes:
  project-database: