version: '3.2'

services:
  php:
    container_name: project-php
    build: ./docker/php/
    image: project-php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www/html
  
  nginx:
    container_name: project-nginx
    build: ./docker/nginx
    image: project-nginx
    ports:
      - 80:80

  mysql:
    container_name: project-mysql
    build: ./docker/mysql
    image: project-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - project-database:/var/lib/mysql

volumes:
  project-database: